source 'https://rubygems.org'

# Provides basic authentication functionality for testing parts of your engine
gem 'spree_auth_devise', :git => 'https://github.com/spree/spree_auth_devise.git', :branch => '2-0-stable'
gem "rest-client", :git => "git://github.com/rest-client/rest-client.git"
gem "spreadsheet", "~> 0.8.3"

gemspec
